# Site settings
title: "Adventurer's Log"
email: amlalejini@gmail.com
baseurl: /adventurer-log-site-template

include:
  - _pages

collections:
  characters:
    output: true
    permalink: /:collection/:title

sass:
  sass_dir: _sass
  style: compressed

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-sitemap